name: Build & Publish Migrations

on:
  push:
    branches:
    - main
    # paths:
    # - "migrations/**"
    # - "Dockerfile"
    # - "scripts/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set version
      id: vars
      run: |
        VERSION=1.0.${{ github.run_number }}
        REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "repo_lower=$REPO_LOWER" >> $GITHUB_OUTPUT

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/${{ steps.vars.outputs.repo_lower }}:${{ steps.vars.outputs.version }} -f Dockerfile .
        docker tag ghcr.io/${{ steps.vars.outputs.repo_lower }}:${{ steps.vars.outputs.version }} ghcr.io/${{ steps.vars.outputs.repo_lower }}:latest

    - name: Push to GHCR
      run: |
        docker push ghcr.io/${{ steps.vars.outputs.repo_lower }}:${{ steps.vars.outputs.version }}
        docker push ghcr.io/${{ steps.vars.outputs.repo_lower }}:latest
